from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

from unittest import TestCase
from idlk import idlk

class IdlkTest(TestCase):

    def test_idlk(self):
        data = (
            ('0.indd',  '~0~8iytu9.idlk'),
            ('1.indd',  '~1~a2)7_x.idlk'),
            ('2.indd',  '~2~bs2r4g.idlk'),
            ('3.indd',  '~3~dc75b$.idlk'),
            ('4.indd',  '~4~e_bojn.idlk'),
            ('5.indd',  '~5~glg2r6.idlk'),
            ('6.indd',  '~6~i5klyu.idlk'),
            ('7.indd',  '~7~jup01d.idlk'),
            ('8.indd',  '~8~letj8_.idlk'),
            ('9.indd',  '~9~m)x(gk.idlk'),
            ('a.indd',  '~a~ddf7)7.idlk'),
            ('b.indd',  '~b~e(jr5v.idlk'),
            ('c.indd',  '~c~gmo5de.idlk'),
            ('d.indd',  '~d~i6sok(.idlk'),
            ('e.indd',  '~e~jvx2sl.idlk'),
            ('f.indd',  '~f~lf_l-4.idlk'),
            ('g.indd',  '~g~n0102s.idlk'),
            ('h.indd',  '~h~op5jab.idlk'),
            ('i.indd',  '~i~q99(hz.idlk'),
            ('j.indd',  '~j~ryegpi.idlk'),
            ('k.indd',  '~k~tiizx1.idlk'),
            ('l.indd',  '~l~v2nd$p.idlk'),
            ('m.indd',  '~m~wrrx78.idlk'),
            ('n.indd',  '~n~ybwbew.idlk'),
            ('o.indd',  '~o~z--umf.idlk'),
            ('p.indd',  '~p~0i3$co.idlk'),
            ('q.indd',  '~q~228ik7.idlk'),
            ('r.indd',  '~r~3rc_rv.idlk'),
            ('s.indd',  '~s~5bhfze.idlk'),
            ('t.indd',  '~t~6-lz1(.idlk'),
            ('u.indd',  '~u~8kqd9l.idlk'),
            ('v.indd',  '~v~a4uwh4.idlk'),
            ('w.indd',  '~w~btzaos.idlk'),
            ('x.indd',  '~x~dd)twb.idlk'),
            ('y.indd',  '~y~e)37)z.idlk'),
            ('z.indd',  '~z~gn7r6i.idlk'),

            ('0.icml',  '~0~8io8_f.idlk'),
            ('1.icml',  '~1~a2ss3).idlk'),
            ('2.icml',  '~2~brx6bm.idlk'),
            ('3.icml',  '~3~db_pj5.idlk'),
            ('4.icml',  '~4~e_13qt.idlk'),
            ('5.icml',  '~5~gl5myc.idlk'),
            ('6.icml',  '~6~i5a10-.idlk'),
            ('7.icml',  '~7~juek8j.idlk'),
            ('8.icml',  '~8~lei)g2.idlk'),
            ('9.icml',  '~9~m)nhnq.idlk'),
            ('a.icml',  '~a~dd4s5d.idlk'),
            ('b.icml',  '~b~e(96c_.idlk'),
            ('c.icml',  '~c~gmdpkk.idlk'),
            ('d.icml',  '~d~i6i3s3.idlk'),
            ('e.icml',  '~e~jvmmzr.idlk'),
            ('f.icml',  '~f~lfr12a.idlk'),
            ('g.icml',  '~g~m$vk9y.idlk'),
            ('h.icml',  '~h~ooz)hh.idlk'),
            ('i.icml',  '~i~q8$hp0.idlk'),
            ('j.icml',  '~j~ry3-wo.idlk'),
            ('k.icml',  '~k~ti8e$7.idlk'),
            ('l.icml',  '~l~v2cy6v.idlk'),
            ('m.icml',  '~m~wrhcee.idlk'),
            ('n.icml',  '~n~yblvl(.idlk'),
            ('o.icml',  '~o~z-q9tl.idlk'),
            ('p.icml',  '~p~0hyjju.idlk'),
            ('q.icml',  '~q~21((rd.idlk'),
            ('r.icml',  '~r~3r2gy_.idlk'),
            ('s.icml',  '~s~5b6-1k.idlk'),
            ('t.icml',  '~t~6-be93.idlk'),
            ('u.icml',  '~u~8kfxgr.idlk'),
            ('v.icml',  '~v~a4kboa.idlk'),
            ('w.icml',  '~w~btouvy.idlk'),
            ('x.icml',  '~x~ddt8)h.idlk'),
            ('y.icml',  '~y~e(xs60.idlk'),
            ('z.icml',  '~z~gm(6do.idlk'),

            ('   ',     '~   ~00uw9x.idlk'),
            ('  !',     '~  !~00uw9y.idlk'),
            ('  "',     '~  "~00uw9z.idlk'),
            ('  ',      '~  ~0004_f.idlk'),
            (' !',      '~ !~0004_g.idlk'),
            (' 0',      '~ 0~0004_v.idlk'),
            ('! ',      '~! ~00052q.idlk'),
            ('!!',      '~!!~00052r.idlk'),
            ('0 ',      '~0 ~0007er.idlk'),
            ('0.indd',  '~0~8iytu9.idlk'),
            ('00',      '~00~0007f2.idlk'),
            ('000',     '~000~0157et.idlk'),
            ('001',     '~001~0157eu.idlk'),
            ('002',     '~002~0157ev.idlk'),
            ('aa',      '~aa~000e-g.idlk'),
            ('~ ',      '~~ ~000jbo.idlk'),
            ('~~',      '~~~~000jd-.idlk'),

            ('0123456789abcdefghijklmnopqrstufvxyz.icml', '~0123456789abcdefgh~weyd6-.idlk'),
        )

        for name, enc in data:
            self.assertEqual(idlk(name), enc)
